name: test de conexion a la base de datos

on:
  push:
    branches:
      - main

jobs:
  test-database-connection:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: ferreteria
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin --host=localhost --user=root --password='root' ping --silent" 
          --health-interval=10s
          --health-timeout=20s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Instalar las dependencias
        run: npm install

      - name: Wait for MySQL
        run: |
          until mysqladmin --host=mysql --user=root --password='root' ping --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Run Mocha tests
        env:
          MYSQL_HOST: 'mysql' 
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'root'
          MYSQL_DATABASE: 'ferreteria'
        run: npx mocha bdd.test.js
