name: test de conexion a la base de datos

on:
  push:
    branches:
      - main

jobs:
  test-database-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Start MySQL Service
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3307
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'ferreteria'
          mysql root password: 'root'
          mysql user: ''
          mysql password: ''

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin --host=localhost --port=3306 ping --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Run Mocha tests
        env:
          MYSQL_HOST: 'localhost'
          MYSQL_PORT: '3306'
          MYSQL_USER: ''
          MYSQL_DATABASE: 'ferreteria'
        run: npx mocha bdd.test.js
